function [BW_out,properties,emptyornot] = filterRegions_one(BW_in,Parameters)
%filterRegions  Filter BW image using auto-generated code from
%imageRegionAnalyzer app. emptyornot is 0 if no areas are quantified given
%the parameters set up in the main function.
%  [BW_OUT,PROPERTIES] = filterRegions(BW_IN) filters binary image BW_IN
%  using auto-generated code from the imageRegionAnalyzer app. BW_OUT has
%  had all of the options and filtering selections that were specified in
%  imageRegionAnalyzer applied to it. The PROPERTIES structure contains the
%  attributes of BW_out that were visible in the app.

% Auto-generated by imageRegionAnalyzer app on 21-Jun-2019
%---------------------------------------------------------

BW_out = imcomplement(imbinarize(BW_in(:,:,1),'adaptive','Sensitivity',Parameters.Sensitivity));

% Remove portions of the image that touch an outside edge.
BW_out = imclearborder(BW_out);

% Filter image based on image properties, ie area.
BW_out = bwpropfilt(BW_out, 'Area', Parameters.QuantRange);

% Get properties.
properties = regionprops(BW_out, {'Area', 'Eccentricity', 'EquivDiameter', 'EulerNumber', 'MajorAxisLength', 'MinorAxisLength', 'Orientation', 'Perimeter'});

% Sort the properties.
properties = sortProperties(properties, 'Area');

% If no areas are quantified, output an error and break out of function

if length(properties) == 0
        
    emptyornot = 0;
    
    return
    
end

emptyornot = 1;

% Uncomment the following line to return the properties in a table.
properties = struct2table(properties);

%writematrix(properties.Area,['Area count'],'FileType', 'spreadsheet')

function properties = sortProperties(properties, sortField)

    % Compute the sort order of the structure based on the sort field.
    [~,idx] = sort([properties.(sortField)], 'descend');

    % Reorder the entire structure.
    properties = properties(idx);
    
end
end